#!/usr/bin/env python3
"""
Build a stylized SVG QR code for the chapter URL.

Renders the QR matrix for `https://pauseai.es` using brand orange
modules, three concentric rounded-rectangle position markers, and the
PauseAI ES mark overlaid in the center. Error correction H (30%) allows
the center logo without breaking scannability.

Run from the repo root:
    python3 scripts/build-qr.py

Writes:
  - brand/qr-pauseai-es.svg                  (canonical standalone QR)
  - designs/<slug>/back.svg                  (full back design template,
                                              regenerated identically
                                              across all design folders)
"""
import re
import sys
from pathlib import Path

try:
    import qrcode
    import qrcode.constants
except ImportError:
    sys.exit("pip install qrcode (or apt install python3-qrcode)")

ROOT = Path(__file__).resolve().parent.parent
URL = "https://pauseai.es"
ORANGE = "#FF9416"
WHITE = "#FFFFFF"
INK = "#111111"

qr = qrcode.QRCode(
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=1,
    border=0,
)
qr.add_data(URL)
qr.make(fit=True)
matrix = qr.get_matrix()
size = len(matrix)

# Pull the chapter mark to drop into the QR center
mark_svg = (ROOT / "brand/logos/pauseai-es-mark.svg").read_text()
m = re.search(r'viewBox="([^"]+)"', mark_svg)
mark_vb = m.group(1) if m else "0 0 905 929"
mi = re.sub(r"<\?xml[^?]*\?>", "", mark_svg)
mi = re.sub(r"<!--.*?-->", "", mi, flags=re.DOTALL)
m = re.search(r"<svg[^>]*>(.*)</svg>", mi, flags=re.DOTALL)
mark_inner = m.group(1).strip() if m else ""


def is_position_marker(r, c):
    return (
        (r < 7 and c < 7)
        or (r < 7 and c >= size - 7)
        or (r >= size - 7 and c < 7)
    )


# Center logo zone — about 20% of QR width, odd-sized for clean centering.
logo_size = max(5, size // 5)
if logo_size % 2 == 0:
    logo_size += 1
center = size // 2
logo_min = center - logo_size // 2
logo_max = logo_min + logo_size - 1


def is_logo_zone(r, c):
    return logo_min <= r <= logo_max and logo_min <= c <= logo_max


def build_qr_svg() -> tuple[str, str, str]:
    """Returns (full_svg, inner_viewbox, inner_content)."""
    # `width`/`height` give the standalone file a useful render size in
    # browsers (without them, browsers default to ~300 px and the QR looks
    # tiny when opened directly). Nested copies in back.svg override these.
    display_px = 800
    # 1 module of white quiet zone — tighter than the QR-spec 4-module
    # recommendation; relies on the back.svg's external white panel
    # adding additional quiet zone when embedded.
    QUIET = 1
    extent = size + 2 * QUIET   # total module-units the SVG covers
    p = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="{-QUIET} {-QUIET} {extent} {extent}" '
        f'width="{display_px}" height="{display_px}">',
        f'  <rect x="{-QUIET}" y="{-QUIET}" '
        f'width="{extent}" height="{extent}" fill="{WHITE}"/>',
        f'  <g fill="{ORANGE}">',
    ]
    for r in range(size):
        for c in range(size):
            if matrix[r][c] and not is_position_marker(r, c) and not is_logo_zone(r, c):
                p.append(f'    <rect x="{c}" y="{r}" width="1" height="1"/>')
    p.append("  </g>")
    for (mr, mc) in [(0, 0), (0, size - 7), (size - 7, 0)]:
        p.append(f'  <g transform="translate({mc} {mr})">')
        p.append(f'    <rect x="0" y="0" width="7" height="7" rx="1.5" fill="{ORANGE}"/>')
        p.append(f'    <rect x="1" y="1" width="5" height="5" rx="1" fill="{WHITE}"/>')
        p.append(f'    <rect x="2" y="2" width="3" height="3" rx="0.5" fill="{ORANGE}"/>')
        p.append("  </g>")
    p.append(
        f'  <rect x="{logo_min}" y="{logo_min}" '
        f'width="{logo_size}" height="{logo_size}" fill="{ORANGE}"/>'
    )
    p.append(
        f'  <svg x="{logo_min + 0.5}" y="{logo_min + 0.5}" '
        f'width="{logo_size - 1}" height="{logo_size - 1}" '
        f'viewBox="{mark_vb}">{mark_inner}</svg>'
    )
    p.append("</svg>")
    body = "\n".join(p)

    standalone = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- Stylized QR for {URL} — generated by scripts/build-qr.py. Do not edit by hand. -->\n"
        + body
        + "\n"
    )
    # Extract inner content for embedding
    m = re.search(r'<svg[^>]*viewBox="([^"]+)"[^>]*>(.*)</svg>', body, flags=re.DOTALL)
    return standalone, m.group(1), m.group(2).strip()


def build_back_svg(qr_vb: str, qr_inner: str) -> str:
    """Full back.svg template — same for every design folder."""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  Back design — stylized QR linking to {URL} plus the URL text.
  Shared across all chapter activist tees. Regenerate with:
      python3 scripts/build-qr.py
  Layout (200 x 200 mm canvas):
    x=55..145, y=30..120   White scan panel (90 x 90 mm)
    x=60..140, y=35..115   QR (80 x 80 mm)
    y=145                  PAUSEAI.ES wordmark
-->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 200 200"
     width="200mm" height="200mm"
     role="img"
     aria-label="QR a pauseai.es">
  <title>pauseai.es</title>

  <rect x="55" y="30" width="90" height="90" fill="{WHITE}"/>

  <svg id="qr" x="60" y="35" width="80" height="80" viewBox="{qr_vb}">
    {qr_inner}
  </svg>

  <text x="100" y="145"
        font-family="Saira Condensed, Impact, sans-serif"
        font-weight="700" font-size="15"
        fill="{WHITE}" text-anchor="middle">PAUSEAI.ES</text>
</svg>
"""


def main():
    standalone, qr_vb, qr_inner = build_qr_svg()

    (ROOT / "brand/qr-pauseai-es.svg").write_text(standalone)
    print(f"QR version {qr.version}, {size}x{size} modules, logo {logo_size}x{logo_size}")
    print("Saved: brand/qr-pauseai-es.svg")

    back_template = build_back_svg(qr_vb, qr_inner)
    for back in sorted((ROOT / "designs").glob("*/back.svg")):
        back.write_text(back_template)
        print(f"Rewrote: designs/{back.parent.name}/back.svg")


if __name__ == "__main__":
    main()
