#!/usr/bin/env python3
"""
Build a stylized SVG QR code for the chapter URLs.

Two languages, two URLs:
  - ES (chapter)  → https://pauseai.es      with the chapter mark in the
                                             QR centre
  - EN (global)   → https://pauseai.info    with the global mark in the
                                             QR centre

Renders each QR matrix using brand orange modules, three concentric
rounded-rectangle position markers, and the appropriate mark overlaid
in the centre. Error correction H (30 %) allows the centre logo
without breaking scannability.

Outputs per language:
  - brand/qr-pauseai-{es,info}.svg        canonical standalone QR
  - designs/<slug>/back{,.en}.svg         orange-tee canonical back
  - designs/<slug>/back{,.en}.white.svg   white-tee variant
  - designs/<slug>/back{,.en}.black.svg   black-tee variant

Run from the repo root:
    python3 scripts/build-qr.py
"""
import re
import sys
from pathlib import Path

try:
    import qrcode
    import qrcode.constants
except ImportError:
    sys.exit("pip install qrcode (or apt install python3-qrcode)")

ROOT = Path(__file__).resolve().parent.parent
ORANGE = "#FF9416"
WHITE = "#FFFFFF"
INK = "#111111"

# Per-tee colour for the panel border + wordmark.
ACCENT_COLOR = {
    "orange": WHITE,
    "white":  ORANGE,
    "black":  ORANGE,
}

# Per-language config: URL, wordmark label, centre-mark logo, output basenames
LANGUAGES = {
    "es": {
        "url": "https://pauseai.es",
        "wordmark": "PAUSEAI.ES",
        "mark_path": "brand/logos/pauseai-es-mark.svg",
        "qr_filename": "brand/qr-pauseai-es.svg",
        "lang": "es",
    },
    "en": {
        "url": "https://pauseai.info",
        "wordmark": "PAUSEAI.INFO",
        "mark_path": "brand/logos/pauseai-global-mark.svg",
        "qr_filename": "brand/qr-pauseai-info.svg",
        "lang": "en",
    },
}


def _load_mark(path):
    """Return (viewBox, inner-content) of a mark SVG."""
    svg = (ROOT / path).read_text()
    vb = re.search(r'viewBox="([^"]+)"', svg)
    vb = vb.group(1) if vb else "0 0 1 1"
    s = re.sub(r"<\?xml[^?]*\?>", "", svg)
    s = re.sub(r"<!--.*?-->", "", s, flags=re.DOTALL)
    m = re.search(r"<svg[^>]*>(.*)</svg>", s, flags=re.DOTALL)
    return vb, (m.group(1).strip() if m else "")


def _build_qr_for(url, mark_vb, mark_inner):
    """Build the QR SVG: (full_svg_str, inner_viewbox, inner_content)."""
    qr = qrcode.QRCode(
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=1, border=0,
    )
    qr.add_data(url)
    qr.make(fit=True)
    matrix = qr.get_matrix()
    size = len(matrix)

    def is_position_marker(r, c):
        return (
            (r < 7 and c < 7)
            or (r < 7 and c >= size - 7)
            or (r >= size - 7 and c < 7)
        )

    logo_size = max(5, size // 5)
    if logo_size % 2 == 0:
        logo_size += 1
    center = size // 2
    logo_min = center - logo_size // 2
    logo_max = logo_min + logo_size - 1

    def is_logo_zone(r, c):
        return logo_min <= r <= logo_max and logo_min <= c <= logo_max

    QUIET = 1
    extent = size + 2 * QUIET
    display_px = 800
    p = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="{-QUIET} {-QUIET} {extent} {extent}" '
        f'width="{display_px}" height="{display_px}">',
        f'  <rect x="{-QUIET}" y="{-QUIET}" '
        f'width="{extent}" height="{extent}" fill="{WHITE}"/>',
        f'  <g fill="{ORANGE}">',
    ]
    for r in range(size):
        for c in range(size):
            if matrix[r][c] and not is_position_marker(r, c) and not is_logo_zone(r, c):
                p.append(f'    <rect x="{c}" y="{r}" width="1" height="1"/>')
    p.append("  </g>")
    for (mr, mc) in [(0, 0), (0, size - 7), (size - 7, 0)]:
        p.append(f'  <g transform="translate({mc} {mr})">')
        p.append(f'    <rect x="0" y="0" width="7" height="7" rx="1.5" fill="{ORANGE}"/>')
        p.append(f'    <rect x="1" y="1" width="5" height="5" rx="1" fill="{WHITE}"/>')
        p.append(f'    <rect x="2" y="2" width="3" height="3" rx="0.5" fill="{ORANGE}"/>')
        p.append("  </g>")
    p.append(
        f'  <rect x="{logo_min}" y="{logo_min}" '
        f'width="{logo_size}" height="{logo_size}" fill="{ORANGE}"/>'
    )
    p.append(
        f'  <svg x="{logo_min + 0.5}" y="{logo_min + 0.5}" '
        f'width="{logo_size - 1}" height="{logo_size - 1}" '
        f'viewBox="{mark_vb}">{mark_inner}</svg>'
    )
    p.append("</svg>")
    body = "\n".join(p)

    standalone = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- Stylized QR for {url} — generated by scripts/build-qr.py. Do not edit by hand. -->\n"
        + body + "\n"
    )
    m = re.search(r'<svg[^>]*viewBox="([^"]+)"[^>]*>(.*)</svg>', body, flags=re.DOTALL)
    return standalone, m.group(1), m.group(2).strip(), qr.version, size, logo_size


def build_back_svg(url, wordmark, qr_vb, qr_inner, tee):
    """Back template for a given URL/wordmark/tee colour."""
    accent = ACCENT_COLOR[tee]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  Back design ({tee} tee, {wordmark}) — stylized QR linking to {url}.
  Regenerate with: python3 scripts/build-qr.py
  Layout (200 x 200 mm canvas):
    x=55..145, y=30..120   White scan panel — fill always WHITE,
                           stroke = {tee}-tee accent colour
    x=60..140, y=35..115   QR (80 x 80 mm) — orange modules, always
    y=145                  Wordmark — accent colour
-->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 200 200"
     width="200mm" height="200mm"
     role="img"
     aria-label="QR to {url}">
  <title>{url} ({tee} tee)</title>

  <rect x="55" y="30" width="90" height="90"
        fill="{WHITE}" stroke="{accent}" stroke-width="4"/>

  <svg id="qr" x="60" y="35" width="80" height="80" viewBox="{qr_vb}">
    {qr_inner}
  </svg>

  <text x="100" y="145"
        font-family="Saira Condensed, Impact, sans-serif"
        font-weight="700" font-size="15"
        fill="{accent}" text-anchor="middle">{wordmark}</text>
</svg>
"""


def main():
    design_dirs = sorted(
        d for d in (ROOT / "designs").iterdir()
        if d.is_dir() and not d.name.startswith("_")
    )

    for lang_code, cfg in LANGUAGES.items():
        mark_vb, mark_inner = _load_mark(cfg["mark_path"])
        standalone, qr_vb, qr_inner, qr_version, size, logo_size = _build_qr_for(
            cfg["url"], mark_vb, mark_inner)

        (ROOT / cfg["qr_filename"]).write_text(standalone)
        print(f"[{lang_code}] QR v{qr_version} {size}x{size}, "
              f"logo {logo_size}x{logo_size} → {cfg['qr_filename']}")

        for design_dir in design_dirs:
            for tee in ("orange", "white", "black"):
                fname = f"{cfg['lang']}.{tee}.back.svg"
                (design_dir / fname).write_text(
                    build_back_svg(cfg["url"], cfg["wordmark"],
                                   qr_vb, qr_inner, tee))
            print(f"  [{lang_code}] {design_dir.name}/{cfg['lang']}.back.*.svg")


if __name__ == "__main__":
    main()
