#!/usr/bin/env python3
"""
Build the single-ink logo lockups from the on-orange variants:

  brand/logos/pauseai-es-on-orange.svg      -> brand/logos/pauseai-es-mono-ink.svg
  brand/logos/pauseai-global-on-orange.svg  -> brand/logos/pauseai-global-mono-ink.svg

The on-orange variant is the right source: its mark cutouts (the P bars,
the ñ-tilde) are already transparent, so turning every white fill to ink
gives a true one-colour lockup with the tee showing through the cutouts.
Used on pale tees (yellow, pastels) where neither orange nor white reads,
and for any one-colour screen print.

In one colour, a letter that touches the mark merges into it: in the ES
lockup the P of PAUSE and the E of EN sit in notches cut into the circle.
So the mark is trimmed by GAP around every letter (each letter dilated
with a round stroke, then subtracted from the mark with skia-pathops).
The letter paths are copied unchanged; only the mark loses a sliver. If
no letter comes within GAP of the mark, the mark is copied unchanged too.

Ink follows each family's own convention: #111111 in the ES files,
`black` in the global ones.

Run from the repo root (needs fontTools + skia-pathops, see SETUP.md):
    python3 scripts/build-mono-logos.py
"""
import re
from pathlib import Path
from xml.etree import ElementTree as ET

import pathops
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path

ROOT = Path(__file__).resolve().parent.parent
LOGOS = ROOT / 'brand/logos'

# Gap as a fraction of the lockup width: 22 units of the ES lockup's 3400,
# about 1 mm when the logo prints 150 mm wide on a chest design.
GAP_FRACTION = 22 / 3400

FAMILIES = {
    'es': {
        'white': '#FFFFFF', 'ink': '#111111',
        'name': 'PauseAI en Español',
        'touching': 'the P of PAUSE and the E of EN sit in notches\n  cut into the circle',
    },
    'global': {
        'white': 'white', 'ink': 'black',
        'name': 'PauseAI',
        'touching': 'the P of Pause overlaps the circle',
    },
}

HEADER = """<!--
  {name}: single-ink lockup (everything {ink}).

  For pale backgrounds where neither orange nor white reads (yellow,
  pastels, light greys) and for any one-colour screen print.

  GENERATED by scripts/build-mono-logos.py from {source}:
  every white fill becomes ink, and the mark is trimmed by a thin gap
  (about 1 mm when the logo prints 150 mm wide) wherever a letter would
  otherwise touch it. Here, {touching}.
  Letter paths are unchanged.

  Fills in this file:
    {ink:<8} ink: mark and wordmark
    none     transparent: cutouts, so the surface shows through

  DO NOT edit by hand. Re-run the script instead.
-->"""

TAG = re.compile(r'<(?:path|rect)\b[^>]*/>')
TRANSLATE = re.compile(r'translate\(\s*([-\d.]+)[\s,]+([-\d.]+)\s*\)')


def to_path(tag):
    """Self-closing <path>/<rect> tag -> (element, pathops.Path)."""
    el = ET.fromstring(tag)
    path = pathops.Path()
    pen = path.getPen()
    if el.get('transform'):
        m = TRANSLATE.fullmatch(el.get('transform').strip())
        assert m, f'unsupported transform: {el.get("transform")}'
        pen = TransformPen(pen, (1, 0, 0, 1, float(m[1]), float(m[2])))
    if el.tag == 'path':
        parse_path(el.get('d'), pen)
    else:
        # Corner radius ignored: rects only feed the cutter, where a
        # sub-unit rx makes no difference.
        x, y, w, h = (float(el.get(k)) for k in ('x', 'y', 'width', 'height'))
        pen.moveTo((x, y))
        pen.lineTo((x + w, y))
        pen.lineTo((x + w, y + h))
        pen.lineTo((x, y + h))
        pen.closePath()
    if el.get('fill-rule') == 'evenodd':
        path.fillType = pathops.FillType.EVEN_ODD
    return el, path


def area_of_bounds(path):
    x0, y0, x1, y1 = path.bounds
    return (x1 - x0) * (y1 - y0)


def to_d(path):
    pen = SVGPathPen(None, ntos=lambda v: f'{v:.2f}'.rstrip('0').rstrip('.'))
    path.draw(pen)
    return pen.getCommands()


def build(family, cfg):
    source = LOGOS / f'pauseai-{family}-on-orange.svg'
    out = LOGOS / f'pauseai-{family}-mono-ink.svg'
    text = source.read_text()

    vb = re.search(r'<svg\b[^>]*viewBox="([^"]+)"', text)[1].split()
    gap = float(vb[2]) * GAP_FRACTION

    shapes = [(tag, *to_path(tag)) for tag in TAG.findall(text)]
    visible = [s for s in shapes if s[1].get('fill') not in (None, 'none')]
    mark_tag, _, mark = max(
        (s for s in visible if s[1].get('fill') == cfg['white']),
        key=lambda s: area_of_bounds(s[2]))

    # Cutter: every letter grown by `gap` on all sides.
    cutter = pathops.Path()
    for tag, _, letter in visible:
        if tag is mark_tag:
            continue
        halo = pathops.Path(letter)
        halo.stroke(2 * gap, pathops.LineCap.ROUND_CAP,
                    pathops.LineJoin.ROUND_JOIN, 4)
        halo.convertConicsToQuads()  # round joins come out as conics
        cutter = pathops.op(cutter, letter, pathops.PathOp.UNION)
        cutter = pathops.op(cutter, halo, pathops.PathOp.UNION)

    overlap = pathops.op(mark, cutter, pathops.PathOp.INTERSECTION)
    if abs(overlap.area) > 1e-3:
        trimmed = pathops.op(mark, cutter, pathops.PathOp.DIFFERENCE)
        rule = ' fill-rule="evenodd"' if trimmed.fillType == pathops.FillType.EVEN_ODD else ''
        new_tag = re.sub(r'\s(?:fill-rule|clip-rule)="[^"]*"', '', mark_tag)
        new_tag = re.sub(r'\sd="[^"]*"', f' d="{to_d(trimmed)}"{rule}', new_tag)
        text = text.replace(mark_tag, new_tag, 1)
        note = f'mark trimmed by a {gap:.1f}-unit gap'
    else:
        note = 'no letter within the gap, mark unchanged'

    text = text.replace(f'fill="{cfg["white"]}"', f'fill="{cfg["ink"]}"')
    assert f'"{cfg["white"]}"' not in text, 'a white fill survived'
    text = re.sub(r'<!--.*?-->', HEADER.format(source=source.name, **cfg),
                  text, count=1, flags=re.DOTALL)
    out.write_text(text)
    print(f'  wrote {out.relative_to(ROOT)}  ({note})')


def main():
    for family, cfg in FAMILIES.items():
        build(family, cfg)


if __name__ == '__main__':
    main()
